### ISSUE TITLE
Breaks VS for Mac 2019 Preferences

### ISSUE THREAD

**Issue by millman82** [mrward/monodevelop-task-runner-addin#10]
When I install the extension in Visual Studio for Mac for either the current stable or preview version (8.3.10 or 8.4 Preview 3 respectively), I am no longer able to launch the Preferences window. Disabling or uninstalling the extension instantly allows me to open the Visual Studio Preferences window.

**Comment by mrward** [comment]
1. Which version of the task runner explorer do you have installed?
2. Can you post the error logged in the IDE log? (Help - Open Log Directory).

With Task Runner Explorer 0.1.2 installed the Preferences dialog opens OK for me in VS Mac 8.3.

Older Task Runner Explorer versions were broken in VS Mac 8.1 since there were some API changes in that version - https://github.com/mrward/monodevelop-task-runner-addin/issues/9

**Comment by millman82** [comment]
Apologies for the late response. I don't seem to be able to reproduce the issue in the latest version of VS Mac 8.5 Preview (build 1543). I just installed the extension again and am still able to open the Preferences dialog. However, the Gallery of the Extension Explorer only shows version 0.1.1 at the present time.

<img width="827" alt="image" src="https://user-images.githubusercontent.com/650498/72449395-94cf9980-3786-11ea-927b-0f78a20ac496.png">

**Comment by mrward** [comment]
There are problems with the addin server. Depending on when the xml is generated for a newer VS Mac version on the server if the addin is published to an older version after this then it is not auto-published for later versions.

I will re-publish them to latest stable and 8.5.

It can also be downloaded directly from - http://addins.monodevelop.com/Project/Index/374

**Comment by millman82** [comment]
Updated extension shows up now. Thanks for your support! Since nothing is interfering with the preferences in VS Mac any longer I consider this resolved. Closing the issue now.
