### ISSUE TITLE
Extension could not be installed

### ISSUE THREAD

**Issue by esausilva** [mrward/monodevelop-task-runner-addin#8]
I'm trying to install this extension but is telling me it can't be installed

```
The selected extension packages can't be installed because there are dependency conflicts. 
The package 'Core v7.5' could not be found in any repository
The package 'Ide v7.5' could not be found in any repository

The following dependencies could not be resolved

Core v7.5
Ide v7.5
```

I'm running the latest Visual Studio Community (v8.0.5 build 9)

Thanks

**Comment by mrward** [comment]
Not sure which version you are installing. There was a problem with Task Runner Explorer 0.1 on the server side since it was returning the extension for VS Mac 7.0 even though the extension itself was OK. I ended up publishing a 0.1.1 version to workaround this problem with the update server.

I just tested VS Mac 8.0.5 and installed Task Runner Explorer 0.1.1 from the extensions manager and it installed without any errors.

I would ensure the addin server has been refreshed - there is a Refresh button - and make sure 0.1.1 is being installed.

Also the .mpack is available to download directory - https://addins.monodevelop.com/Project/Index/374

**Comment by esausilva** [comment]
Thank you, I was able to install it from the link you provided. I originally downloaded the file from your blog here https://lastexitcode.com/blog/2019/01/04/TaskRunnerExplorerInVisualStudioMac/

Do you have a link to the updated version for the Task Runners Bundle? or the NPM and Gulp Task Runners? I was not able to find the new release on Github or the link you sent.

Thanks

**Comment by mrward** [comment]
Task Runners Bundle can be downloaded from:

http://addins.monodevelop.com/Project/Index/375

I also publish the .mpacks to my own monodevelop addin repository. Addin .mpacks can be downloaded directly from there:

https://github.com/mrward/monodevelop-addins/tree/gh-pages

Or you can add the url for the feed.

**Comment by esausilva** [comment]
Thank you
